defaults:
  - override hydra/launcher: slurm

# Experiments
args:
  ldim: ~
  model_name: ~
  num_sequences: 10000
  max_length: 512
  test: ~
  data_dir: /scratch/mr7401/datasets/
  use_local_weights: True

command: ~
tags: ~


### Logging 
logging:
  logger: wandb # options: 'local', 'wandb', 'both'. Empty for no logging
  project: meta_comp 
  run_name: generative_${args.num_sequences}_${args.max_length}_${oc.select:hydra.launcher.date,${now:%%m-%d}}
  log_dir: /scratch/mr7401/logs/${logging.project}

hydra:
  launcher:
    cpus_per_task: 2
    mem: 150G
    gres: gpu:1
    container: singularity
    singularity_img: /scratch/work/public/singularity/cuda12.1.1-cudnn8.9.0-devel-ubuntu22.04.2.sif
    singularity_overlay: /scratch/mr7401/projects/pytorch-example/overlay-50G-10M.ext3 
    env_type: conda
    env_name: test
##### SUGGESTED HYDRA CONFIG ###########################
  sweep: 
    # subdir is built dynamically using the tags
    dir: ${logging.log_dir}/outputs/${logging.run_name}
  run:
    # once we're running set tags from conf
    dir: ${hydra.sweep.dir}/${join:${tags}}
########################################################
      #partition: gpu

