defaults:
  - override hydra/launcher: slurm

# Experiments
tags: ~
ldim: ~
command: ~
model_name: ~
num_generations: ~
test: 5

### Logging 
logger: wandb # options: 'local', 'wandb', 'both'. Empty for no logging
project: meta_comp 
run_name: test
log_dir: /scratch/mr7401/logs/${project}

hydra:
  launcher:
    cpus_per_task: 2
    mem: 15G
    gres: gpu:1
    container: singularity
    singularity_img: /scratch/work/public/singularity/cuda12.1.1-cudnn8.9.0-devel-ubuntu22.04.2.sif
    singularity_overlay: /scratch/mr7401/projects/pytorch-example/overlay-50G-10M.ext3 
    env_type: conda
    env_name: test
##### SUGGESTED HYDRA CONFIG ###########################
  sweep: 
    # subdir is built dynamically using the tags
    dir: ${log_dir}/outputs/${run_name}
  run:
    # once we're running set tags from conf
    dir: ${hydra.sweep.dir}/${join:${tags}}
########################################################
      #partition: gpu

