defaults:
  - override hydra/launcher: slurm

# Experiment Arguments
args:
  ldim: ~
  model_name: ~
  model_name2: ~
  num_generations: ~
  max_length: ~
  test: False # If True, models are loaded but no generation is made. 
  data_dir: ~ # used by the LLM generation to identify where to save generated text
  save_dir: ~ # used by VAE generation to identify where to save generated images. #TODO: Align these scripts
  checkpoint_dir: ~ # overwrite default weight loading directory
  use_local_weights: False # If True and we have a local path for the model, local weights will be used. 
  n_subset: ~
  MN: ~ 
  epoch_to_use: ~

command: ~
tags: ~

### Logging 
logging:
  logger: wandb # options: 'local', 'wandb', 'both'. Empty for no logging
  project: meta_comp 
  experiment: ~
  run_name: ${oc.select:hydra.launcher.date,${now:%%m-%d-%%I%p}}
  log_dir: /scratch/mr7401/logs/${logging.project}
m1: ~
m2: ~
test: ~

hydra:
  launcher:
    cpus_per_task: 1
    mem: 1G
    gres: gpu:1
    container: singularity
#    singularity_img: /scratch/work/public/singularity/cuda12.1.1-cudnn8.9.0-devel-ubuntu22.04.2.sif
#    singularity_overlay: /scratch/nhn234/singularity/aga.ext3
    singularity_img: /scratch/work/public/singularity/cuda12.1.1-cudnn8.9.0-devel-ubuntu22.04.2.sif # /scratch/work/public/singularity/cuda11.6.124-cudnn8.4.0.27-devel-ubuntu20.04.4.sif
    singularity_overlay: /scratch/mr7401/projects/pytorch-example/overlay-50G-10M.ext3 #/scratch/nhn234/singularity/lookahead.ext3
    env_type: conda
    env_name: test #unsloth_env
    time: 240
    job_name: ${logging.experiment}
    #partition: ~ #a100_1,a100_2

##### SUGGESTED HYDRA CONFIG ###########################
  sweep: 
    # subdir is built dynamically using the tags
    dir: ${logging.log_dir}/outputs/${logging.experiment}/${logging.run_name}
  run:
    # once we're running set tags from conf
    dir: ${hydra.sweep.dir}/${join:${tags}}
########################################################
      #partition: gpu

### Launching info to remember 
# A100 partitions we can run on: cds_a100_2,a100_1,a100_2
