# Made by running conda env export | grep -v "^prefix: " > environment.yml
channels:
  - pytorch
  - nvidia
  - conda-forge
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=4.5
  - blas=2.116
  - blas-devel=3.9.0
  - brotli-python=1.1.0
  - bzip2=1.0.8
  - ca-certificates=2024.12.14
  - certifi=2024.12.14
  - cffi=1.17.1
  - charset-normalizer=3.4.1
  - cuda-cudart=12.1.105
  - cuda-cupti=12.1.105
  - cuda-libraries=12.1.0
  - cuda-nvrtc=12.1.105
  - cuda-nvtx=12.1.105
  - cuda-opencl=12.6.77
  - cuda-runtime=12.1.0
  - cuda-version=12.6
  - ffmpeg=4.3
  - filelock=3.16.1
  - freetype=2.12.1
  - giflib=5.2.2
  - gmp=6.3.0
  - gmpy2=2.1.5
  - gnutls=3.6.13
  - h2=4.1.0
  - hpack=4.0.0
  - hyperframe=6.0.1
  - icu=73.2
  - idna=3.10
  - jinja2=3.1.5
  - lame=3.100
  - lcms2=2.16
  - ld_impl_linux-64=2.43
  - lerc=4.0.0
  - libblas=3.9.0
  - libcblas=3.9.0
  - libcublas=12.1.0.26
  - libcufft=11.0.2.4
  - libcufile=1.11.1.6
  - libcurand=10.3.7.77
  - libcusolver=11.4.4.55
  - libcusparse=12.0.2.55
  - libdeflate=1.20
  - libexpat=2.6.4
  - libffi=3.4.2
  - libgcc=14.2.0
  - libgcc-ng=14.2.0
  - libgfortran=14.2.0
  - libgfortran-ng=14.2.0
  - libgfortran5=14.2.0
  - libhwloc=2.11.2
  - libiconv=1.17
  - libjpeg-turbo=3.0.0
  - liblapack=3.9.0
  - liblapacke=3.9.0
  - liblzma=5.6.3
  - liblzma-devel=5.6.3
  - libnpp=12.0.2.50
  - libnsl=2.0.1
  - libnvjitlink=12.1.105
  - libnvjpeg=12.1.1.14
  - libpng=1.6.43
  - libsqlite=3.46.0
  - libstdcxx=14.2.0
  - libstdcxx-ng=14.2.0
  - libtiff=4.6.0
  - libuuid=2.38.1
  - libwebp=1.4.0
  - libwebp-base=1.4.0
  - libxcb=1.15
  - libxcrypt=4.4.36
  - libxml2=2.12.7
  - libzlib=1.2.13
  - llvm-openmp=15.0.7
  - markupsafe=3.0.2
  - mkl=2022.1.0
  - mkl-devel=2022.1.0
  - mkl-include=2022.1.0
  - mpc=1.3.1
  - mpfr=4.2.1
  - mpmath=1.3.0
  - ncurses=6.5
  - nettle=3.6
  - networkx=3.4.2
  - numpy=2.2.1
  - openh264=2.1.1
  - openjpeg=2.5.2
  - openssl=3.4.0
  - pillow=10.3.0
  - pip=24.3.1
  - pthread-stubs=0.4
  - pycparser=2.22
  - pysocks=1.7.1
  - python=3.12.3
  - python_abi=3.12
  - pytorch=2.5.1
  - pytorch-cuda=12.1
  - pytorch-mutex=1.0
  - pyyaml=6.0.2
  - readline=8.2
  - requests=2.32.3
  - setuptools=75.8.0
  - sympy=1.13.3
  - tbb=2021.13.0
  - tk=8.6.13
  - torchaudio=2.5.1
  - torchtriton=3.1.0
  - torchvision=0.20.1
  - typing_extensions=4.12.2
  - tzdata=2024b
  - urllib3=2.3.0
  - wheel=0.45.1
  - xorg-libxau=1.0.12
  - xorg-libxdmcp=1.1.5
  - xz=5.6.3
  - xz-gpl-tools=5.6.3
  - xz-tools=5.6.3
  - yaml=0.2.5
  - zlib=1.2.13
  - zstandard=0.23.0
  - zstd=1.5.6
  - pip:
      - antlr4-python3-runtime==4.9.3
      - fsspec==2024.12.0
      - huggingface-hub==0.28.0
      - hydra-core==1.3.2
      - omegaconf==2.3.0
      - packaging==24.2
      - regex==2024.11.6
      - safetensors==0.5.2
      - tokenizers==0.21.0
      - tqdm==4.67.1
      - transformers==4.48.1
